//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 07:18:43 AM IST 
//


package com.lumendata.model.publish;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Contact_CommunicationAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contact_CommunicationAddress"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AlternateEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CommunicationAddressId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationAddressIntegrationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationAddressMediumType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationAddressName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationAddressUseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Updated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EffectiveEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UpdatedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EffectiveStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LogicalDeleteFlg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationAddressEffectiveStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CommunicationAddressEffectiveEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ListOfCIFCommunicationAddressReference" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfCIFCommunicationAddressReference" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="IsPrimaryMVG" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Operation" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Searchspec" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contact_CommunicationAddress", propOrder = {
    "alternateEmailAddress",
    "communicationAddressId",
    "communicationAddressIntegrationId",
    "communicationAddressMediumType",
    "communicationAddressName",
    "useType",
    "communicationAddressUseType",
    "updated",
    "effectiveEndDate",
    "updatedBy",
    "effectiveStartDate",
    "logicalDeleteFlg",
    "communicationAddressEffectiveStartDate",
    "communicationAddressEffectiveEndDate",
    "listOfCIFCommunicationAddressReference"
})
public class ContactCommunicationAddress {

    @XmlElement(name = "AlternateEmailAddress", required = true)
    protected String alternateEmailAddress;
    @XmlElement(name = "CommunicationAddressId")
    protected String communicationAddressId;
    @XmlElement(name = "CommunicationAddressIntegrationId")
    protected String communicationAddressIntegrationId;
    @XmlElement(name = "CommunicationAddressMediumType")
    protected String communicationAddressMediumType;
    @XmlElement(name = "CommunicationAddressName")
    protected String communicationAddressName;
    @XmlElement(name = "UseType")
    protected String useType;
    @XmlElement(name = "CommunicationAddressUseType")
    protected String communicationAddressUseType;
    @XmlElement(name = "Updated")
    protected String updated;
    @XmlElement(name = "EffectiveEndDate")
    protected String effectiveEndDate;
    @XmlElement(name = "UpdatedBy")
    protected String updatedBy;
    @XmlElement(name = "EffectiveStartDate")
    protected String effectiveStartDate;
    @XmlElement(name = "LogicalDeleteFlg")
    protected String logicalDeleteFlg;
    @XmlElement(name = "CommunicationAddressEffectiveStartDate")
    protected String communicationAddressEffectiveStartDate;
    @XmlElement(name = "CommunicationAddressEffectiveEndDate")
    protected String communicationAddressEffectiveEndDate;
    @XmlElement(name = "ListOfCIFCommunicationAddressReference")
    protected ListOfCIFCommunicationAddressReference listOfCIFCommunicationAddressReference;
    @XmlAttribute(name = "IsPrimaryMVG")
    protected String isPrimaryMVG;
    @XmlAttribute(name = "Operation")
    protected String operation;
    @XmlAttribute(name = "Searchspec")
    protected String searchspec;

    /**
     * Gets the value of the alternateEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateEmailAddress() {
        return alternateEmailAddress;
    }

    /**
     * Sets the value of the alternateEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateEmailAddress(String value) {
        this.alternateEmailAddress = value;
    }

    /**
     * Gets the value of the communicationAddressId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunicationAddressId() {
        return communicationAddressId;
    }

    /**
     * Sets the value of the communicationAddressId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunicationAddressId(String value) {
        this.communicationAddressId = value;
    }

    /**
     * Gets the value of the communicationAddressIntegrationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunicationAddressIntegrationId() {
        return communicationAddressIntegrationId;
    }

    /**
     * Sets the value of the communicationAddressIntegrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunicationAddressIntegrationId(String value) {
        this.communicationAddressIntegrationId = value;
    }

    /**
     * Gets the value of the communicationAddressMediumType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunicationAddressMediumType() {
        return communicationAddressMediumType;
    }

    /**
     * Sets the value of the communicationAddressMediumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunicationAddressMediumType(String value) {
        this.communicationAddressMediumType = value;
    }

    /**
     * Gets the value of the communicationAddressName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunicationAddressName() {
        return communicationAddressName;
    }

    /**
     * Sets the value of the communicationAddressName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunicationAddressName(String value) {
        this.communicationAddressName = value;
    }

    /**
     * Gets the value of the useType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseType() {
        return useType;
    }

    /**
     * Sets the value of the useType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseType(String value) {
        this.useType = value;
    }

    /**
     * Gets the value of the communicationAddressUseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunicationAddressUseType() {
        return communicationAddressUseType;
    }

    /**
     * Sets the value of the communicationAddressUseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunicationAddressUseType(String value) {
        this.communicationAddressUseType = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdated(String value) {
        this.updated = value;
    }

    /**
     * Gets the value of the effectiveEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveEndDate() {
        return effectiveEndDate;
    }

    /**
     * Sets the value of the effectiveEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveEndDate(String value) {
        this.effectiveEndDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedBy(String value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the effectiveStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveStartDate() {
        return effectiveStartDate;
    }

    /**
     * Sets the value of the effectiveStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveStartDate(String value) {
        this.effectiveStartDate = value;
    }

    /**
     * Gets the value of the logicalDeleteFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalDeleteFlg() {
        return logicalDeleteFlg;
    }

    /**
     * Sets the value of the logicalDeleteFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalDeleteFlg(String value) {
        this.logicalDeleteFlg = value;
    }

    /**
     * Gets the value of the communicationAddressEffectiveStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunicationAddressEffectiveStartDate() {
        return communicationAddressEffectiveStartDate;
    }

    /**
     * Sets the value of the communicationAddressEffectiveStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunicationAddressEffectiveStartDate(String value) {
        this.communicationAddressEffectiveStartDate = value;
    }

    /**
     * Gets the value of the communicationAddressEffectiveEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommunicationAddressEffectiveEndDate() {
        return communicationAddressEffectiveEndDate;
    }

    /**
     * Sets the value of the communicationAddressEffectiveEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommunicationAddressEffectiveEndDate(String value) {
        this.communicationAddressEffectiveEndDate = value;
    }

    /**
     * Gets the value of the listOfCIFCommunicationAddressReference property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfCIFCommunicationAddressReference }
     *     
     */
    public ListOfCIFCommunicationAddressReference getListOfCIFCommunicationAddressReference() {
        return listOfCIFCommunicationAddressReference;
    }

    /**
     * Sets the value of the listOfCIFCommunicationAddressReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfCIFCommunicationAddressReference }
     *     
     */
    public void setListOfCIFCommunicationAddressReference(ListOfCIFCommunicationAddressReference value) {
        this.listOfCIFCommunicationAddressReference = value;
    }

    /**
     * Gets the value of the isPrimaryMVG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPrimaryMVG() {
        return isPrimaryMVG;
    }

    /**
     * Sets the value of the isPrimaryMVG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPrimaryMVG(String value) {
        this.isPrimaryMVG = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the searchspec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchspec() {
        return searchspec;
    }

    /**
     * Sets the value of the searchspec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchspec(String value) {
        this.searchspec = value;
    }

}
