//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 07:18:43 AM IST 
//


package com.lumendata.model.publish;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Contact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contact"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Updated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Alias" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Assistant" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AssistantPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BestCallTime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CellularPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CustomerValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="BirthDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmailAddress2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FaxPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FirstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HomePhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Income" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IncomeCurrencyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IncomeExchangeDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IntegrationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="JobTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="LastUpdateSDQ" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MF" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MM2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManagerFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManagerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManagerIntegrationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManagerLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManagerMiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ManagerPrimaryOrganization" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MaritalStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MotherMaidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PartyUId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PersonUId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreferredCommunications" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PreferredLanguageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PrivacyCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SocialSecurityNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SuppressAllCalls" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SuppressAllEmails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SuppressAllFaxes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SuppressAllMailings" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TimeZoneName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WorkPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WorkPhoneExtension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UpdatedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AIAUCMIntegrationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ConsumerLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeceasedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeathCertificateNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PlaceOfDeath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VABenefit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Ethnicity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ClassYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Degree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MaritalStatusDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PendingReviewStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LeadContactType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PartyTypeCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PlaceofBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VABenefits" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ListOfContact_CommunicationAddress" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfContact_CommunicationAddress" minOccurs="0"/&gt;
 *         &lt;element name="ListOfContact_AlternatePhone" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfContact_AlternatePhone" minOccurs="0"/&gt;
 *         &lt;element name="ListOfCuUcmHeConstituentName" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfCuUcmHeConstituentName" minOccurs="0"/&gt;
 *         &lt;element name="ListOfCIFContactReference" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfCIFContactReference" minOccurs="0"/&gt;
 *         &lt;element name="ListOfCuUcmHeConstituentIdentification" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfCuUcmHeConstituentIdentification" minOccurs="0"/&gt;
 *         &lt;element name="ListOfCuUcmHeConstituentAddress" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfCuUcmHeConstituentAddress" minOccurs="0"/&gt;
 *         &lt;element name="ListOfCuUcmHeConstituentAffiliation" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfCuUcmHeConstituentAffiliation" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Operation" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Searchspec" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contact", propOrder = {
    "id",
    "updated",
    "alias",
    "assistant",
    "assistantPhone",
    "bestCallTime",
    "cellularPhone",
    "customerValue",
    "birthDate",
    "emailAddress",
    "emailAddress2",
    "faxPhone",
    "firstName",
    "homePhone",
    "income",
    "incomeCurrencyCode",
    "incomeExchangeDate",
    "integrationId",
    "jobTitle",
    "lastName",
    "lastUpdateSDQ",
    "mf",
    "mm2",
    "managerFirstName",
    "managerId",
    "managerIntegrationId",
    "managerLastName",
    "managerMiddleName",
    "managerPrimaryOrganization",
    "maritalStatus",
    "middleName",
    "motherMaidenName",
    "partyUId",
    "personUId",
    "preferredCommunications",
    "preferredLanguageCode",
    "privacyCode",
    "socialSecurityNumber",
    "status",
    "suppressAllCalls",
    "suppressAllEmails",
    "suppressAllFaxes",
    "suppressAllMailings",
    "timeZoneName",
    "workPhone",
    "workPhoneExtension",
    "updatedBy",
    "aiaucmIntegrationId",
    "consumerLink",
    "deceasedDate",
    "deathCertificateNumber",
    "placeOfDeath",
    "vaBenefit",
    "ethnicity",
    "classYear",
    "degree",
    "maritalStatusDate",
    "pendingReviewStatus",
    "leadContactType",
    "partyTypeCode",
    "placeofBirth",
    "vaBenefits",
    "listOfContactCommunicationAddress",
    "listOfContactAlternatePhone",
    "listOfCuUcmHeConstituentName",
    "listOfCIFContactReference",
    "listOfCuUcmHeConstituentIdentification",
    "listOfCuUcmHeConstituentAddress",
    "listOfCuUcmHeConstituentAffiliation"
})
public class Contact {

    @XmlElement(name = "Id")
    protected String id;
    @XmlElement(name = "Updated")
    protected String updated;
    @XmlElement(name = "Alias")
    protected String alias;
    @XmlElement(name = "Assistant")
    protected String assistant;
    @XmlElement(name = "AssistantPhone")
    protected String assistantPhone;
    @XmlElement(name = "BestCallTime")
    protected String bestCallTime;
    @XmlElement(name = "CellularPhone")
    protected String cellularPhone;
    @XmlElement(name = "CustomerValue")
    protected String customerValue;
    @XmlElement(name = "BirthDate")
    protected String birthDate;
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;
    @XmlElement(name = "EmailAddress2")
    protected String emailAddress2;
    @XmlElement(name = "FaxPhone")
    protected String faxPhone;
    @XmlElement(name = "FirstName", required = true)
    protected String firstName;
    @XmlElement(name = "HomePhone")
    protected String homePhone;
    @XmlElement(name = "Income")
    protected String income;
    @XmlElement(name = "IncomeCurrencyCode")
    protected String incomeCurrencyCode;
    @XmlElement(name = "IncomeExchangeDate")
    protected String incomeExchangeDate;
    @XmlElement(name = "IntegrationId")
    protected String integrationId;
    @XmlElement(name = "JobTitle")
    protected String jobTitle;
    @XmlElement(name = "LastName", required = true)
    protected String lastName;
    @XmlElement(name = "LastUpdateSDQ")
    protected String lastUpdateSDQ;
    @XmlElement(name = "MF")
    protected String mf;
    @XmlElement(name = "MM2")
    protected String mm2;
    @XmlElement(name = "ManagerFirstName")
    protected String managerFirstName;
    @XmlElement(name = "ManagerId")
    protected String managerId;
    @XmlElement(name = "ManagerIntegrationId")
    protected String managerIntegrationId;
    @XmlElement(name = "ManagerLastName")
    protected String managerLastName;
    @XmlElement(name = "ManagerMiddleName")
    protected String managerMiddleName;
    @XmlElement(name = "ManagerPrimaryOrganization")
    protected String managerPrimaryOrganization;
    @XmlElement(name = "MaritalStatus")
    protected String maritalStatus;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "MotherMaidenName")
    protected String motherMaidenName;
    @XmlElement(name = "PartyUId")
    protected String partyUId;
    @XmlElement(name = "PersonUId")
    protected String personUId;
    @XmlElement(name = "PreferredCommunications")
    protected String preferredCommunications;
    @XmlElement(name = "PreferredLanguageCode")
    protected String preferredLanguageCode;
    @XmlElement(name = "PrivacyCode")
    protected String privacyCode;
    @XmlElement(name = "SocialSecurityNumber")
    protected String socialSecurityNumber;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "SuppressAllCalls")
    protected String suppressAllCalls;
    @XmlElement(name = "SuppressAllEmails")
    protected String suppressAllEmails;
    @XmlElement(name = "SuppressAllFaxes")
    protected String suppressAllFaxes;
    @XmlElement(name = "SuppressAllMailings")
    protected String suppressAllMailings;
    @XmlElement(name = "TimeZoneName")
    protected String timeZoneName;
    @XmlElement(name = "WorkPhone")
    protected String workPhone;
    @XmlElement(name = "WorkPhoneExtension")
    protected String workPhoneExtension;
    @XmlElement(name = "UpdatedBy")
    protected String updatedBy;
    @XmlElement(name = "AIAUCMIntegrationId")
    protected String aiaucmIntegrationId;
    @XmlElement(name = "ConsumerLink")
    protected String consumerLink;
    @XmlElement(name = "DeceasedDate")
    protected String deceasedDate;
    @XmlElement(name = "DeathCertificateNumber")
    protected String deathCertificateNumber;
    @XmlElement(name = "PlaceOfDeath")
    protected String placeOfDeath;
    @XmlElement(name = "VABenefit")
    protected String vaBenefit;
    @XmlElement(name = "Ethnicity")
    protected String ethnicity;
    @XmlElement(name = "ClassYear")
    protected String classYear;
    @XmlElement(name = "Degree")
    protected String degree;
    @XmlElement(name = "MaritalStatusDate")
    protected String maritalStatusDate;
    @XmlElement(name = "PendingReviewStatus")
    protected String pendingReviewStatus;
    @XmlElement(name = "LeadContactType", required = true)
    protected String leadContactType;
    @XmlElement(name = "PartyTypeCode", required = true)
    protected String partyTypeCode;
    @XmlElement(name = "PlaceofBirth")
    protected String placeofBirth;
    @XmlElement(name = "VABenefits")
    protected String vaBenefits;
    @XmlElement(name = "ListOfContact_CommunicationAddress")
    protected ListOfContactCommunicationAddress listOfContactCommunicationAddress;
    @XmlElement(name = "ListOfContact_AlternatePhone")
    protected ListOfContactAlternatePhone listOfContactAlternatePhone;
    @XmlElement(name = "ListOfCuUcmHeConstituentName")
    protected ListOfCuUcmHeConstituentName listOfCuUcmHeConstituentName;
    @XmlElement(name = "ListOfCIFContactReference")
    protected ListOfCIFContactReference listOfCIFContactReference;
    @XmlElement(name = "ListOfCuUcmHeConstituentIdentification")
    protected ListOfCuUcmHeConstituentIdentification listOfCuUcmHeConstituentIdentification;
    @XmlElement(name = "ListOfCuUcmHeConstituentAddress")
    protected ListOfCuUcmHeConstituentAddress listOfCuUcmHeConstituentAddress;
    @XmlElement(name = "ListOfCuUcmHeConstituentAffiliation")
    protected ListOfCuUcmHeConstituentAffiliation listOfCuUcmHeConstituentAffiliation;
    @XmlAttribute(name = "Operation")
    protected String operation;
    @XmlAttribute(name = "Searchspec")
    protected String searchspec;
    @XmlAttribute(name = "status")
    protected String contactStatus;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdated(String value) {
        this.updated = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlias() {
        return alias;
    }

    /**
     * Sets the value of the alias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlias(String value) {
        this.alias = value;
    }

    /**
     * Gets the value of the assistant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssistant() {
        return assistant;
    }

    /**
     * Sets the value of the assistant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssistant(String value) {
        this.assistant = value;
    }

    /**
     * Gets the value of the assistantPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssistantPhone() {
        return assistantPhone;
    }

    /**
     * Sets the value of the assistantPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssistantPhone(String value) {
        this.assistantPhone = value;
    }

    /**
     * Gets the value of the bestCallTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBestCallTime() {
        return bestCallTime;
    }

    /**
     * Sets the value of the bestCallTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBestCallTime(String value) {
        this.bestCallTime = value;
    }

    /**
     * Gets the value of the cellularPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellularPhone() {
        return cellularPhone;
    }

    /**
     * Sets the value of the cellularPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellularPhone(String value) {
        this.cellularPhone = value;
    }

    /**
     * Gets the value of the customerValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerValue() {
        return customerValue;
    }

    /**
     * Sets the value of the customerValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerValue(String value) {
        this.customerValue = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBirthDate(String value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the emailAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress2() {
        return emailAddress2;
    }

    /**
     * Sets the value of the emailAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress2(String value) {
        this.emailAddress2 = value;
    }

    /**
     * Gets the value of the faxPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxPhone() {
        return faxPhone;
    }

    /**
     * Sets the value of the faxPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxPhone(String value) {
        this.faxPhone = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the homePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePhone() {
        return homePhone;
    }

    /**
     * Sets the value of the homePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePhone(String value) {
        this.homePhone = value;
    }

    /**
     * Gets the value of the income property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncome() {
        return income;
    }

    /**
     * Sets the value of the income property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncome(String value) {
        this.income = value;
    }

    /**
     * Gets the value of the incomeCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeCurrencyCode() {
        return incomeCurrencyCode;
    }

    /**
     * Sets the value of the incomeCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeCurrencyCode(String value) {
        this.incomeCurrencyCode = value;
    }

    /**
     * Gets the value of the incomeExchangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomeExchangeDate() {
        return incomeExchangeDate;
    }

    /**
     * Sets the value of the incomeExchangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomeExchangeDate(String value) {
        this.incomeExchangeDate = value;
    }

    /**
     * Gets the value of the integrationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntegrationId() {
        return integrationId;
    }

    /**
     * Sets the value of the integrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntegrationId(String value) {
        this.integrationId = value;
    }

    /**
     * Gets the value of the jobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * Sets the value of the jobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTitle(String value) {
        this.jobTitle = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the lastUpdateSDQ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastUpdateSDQ() {
        return lastUpdateSDQ;
    }

    /**
     * Sets the value of the lastUpdateSDQ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastUpdateSDQ(String value) {
        this.lastUpdateSDQ = value;
    }

    /**
     * Gets the value of the mf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMF() {
        return mf;
    }

    /**
     * Sets the value of the mf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMF(String value) {
        this.mf = value;
    }

    /**
     * Gets the value of the mm2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMM2() {
        return mm2;
    }

    /**
     * Sets the value of the mm2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMM2(String value) {
        this.mm2 = value;
    }

    /**
     * Gets the value of the managerFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerFirstName() {
        return managerFirstName;
    }

    /**
     * Sets the value of the managerFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerFirstName(String value) {
        this.managerFirstName = value;
    }

    /**
     * Gets the value of the managerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerId() {
        return managerId;
    }

    /**
     * Sets the value of the managerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerId(String value) {
        this.managerId = value;
    }

    /**
     * Gets the value of the managerIntegrationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerIntegrationId() {
        return managerIntegrationId;
    }

    /**
     * Sets the value of the managerIntegrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerIntegrationId(String value) {
        this.managerIntegrationId = value;
    }

    /**
     * Gets the value of the managerLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerLastName() {
        return managerLastName;
    }

    /**
     * Sets the value of the managerLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerLastName(String value) {
        this.managerLastName = value;
    }

    /**
     * Gets the value of the managerMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerMiddleName() {
        return managerMiddleName;
    }

    /**
     * Sets the value of the managerMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerMiddleName(String value) {
        this.managerMiddleName = value;
    }

    /**
     * Gets the value of the managerPrimaryOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerPrimaryOrganization() {
        return managerPrimaryOrganization;
    }

    /**
     * Sets the value of the managerPrimaryOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerPrimaryOrganization(String value) {
        this.managerPrimaryOrganization = value;
    }

    /**
     * Gets the value of the maritalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Sets the value of the maritalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatus(String value) {
        this.maritalStatus = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the motherMaidenName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotherMaidenName() {
        return motherMaidenName;
    }

    /**
     * Sets the value of the motherMaidenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotherMaidenName(String value) {
        this.motherMaidenName = value;
    }

    /**
     * Gets the value of the partyUId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyUId() {
        return partyUId;
    }

    /**
     * Sets the value of the partyUId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyUId(String value) {
        this.partyUId = value;
    }

    /**
     * Gets the value of the personUId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonUId() {
        return personUId;
    }

    /**
     * Sets the value of the personUId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonUId(String value) {
        this.personUId = value;
    }

    /**
     * Gets the value of the preferredCommunications property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredCommunications() {
        return preferredCommunications;
    }

    /**
     * Sets the value of the preferredCommunications property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredCommunications(String value) {
        this.preferredCommunications = value;
    }

    /**
     * Gets the value of the preferredLanguageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredLanguageCode() {
        return preferredLanguageCode;
    }

    /**
     * Sets the value of the preferredLanguageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredLanguageCode(String value) {
        this.preferredLanguageCode = value;
    }

    /**
     * Gets the value of the privacyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivacyCode() {
        return privacyCode;
    }

    /**
     * Sets the value of the privacyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivacyCode(String value) {
        this.privacyCode = value;
    }

    /**
     * Gets the value of the socialSecurityNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSocialSecurityNumber() {
        return socialSecurityNumber;
    }

    /**
     * Sets the value of the socialSecurityNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSocialSecurityNumber(String value) {
        this.socialSecurityNumber = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the suppressAllCalls property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressAllCalls() {
        return suppressAllCalls;
    }

    /**
     * Sets the value of the suppressAllCalls property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressAllCalls(String value) {
        this.suppressAllCalls = value;
    }

    /**
     * Gets the value of the suppressAllEmails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressAllEmails() {
        return suppressAllEmails;
    }

    /**
     * Sets the value of the suppressAllEmails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressAllEmails(String value) {
        this.suppressAllEmails = value;
    }

    /**
     * Gets the value of the suppressAllFaxes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressAllFaxes() {
        return suppressAllFaxes;
    }

    /**
     * Sets the value of the suppressAllFaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressAllFaxes(String value) {
        this.suppressAllFaxes = value;
    }

    /**
     * Gets the value of the suppressAllMailings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressAllMailings() {
        return suppressAllMailings;
    }

    /**
     * Sets the value of the suppressAllMailings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressAllMailings(String value) {
        this.suppressAllMailings = value;
    }

    /**
     * Gets the value of the timeZoneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZoneName() {
        return timeZoneName;
    }

    /**
     * Sets the value of the timeZoneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZoneName(String value) {
        this.timeZoneName = value;
    }

    /**
     * Gets the value of the workPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkPhone() {
        return workPhone;
    }

    /**
     * Sets the value of the workPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkPhone(String value) {
        this.workPhone = value;
    }

    /**
     * Gets the value of the workPhoneExtension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkPhoneExtension() {
        return workPhoneExtension;
    }

    /**
     * Sets the value of the workPhoneExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkPhoneExtension(String value) {
        this.workPhoneExtension = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedBy(String value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the aiaucmIntegrationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAIAUCMIntegrationId() {
        return aiaucmIntegrationId;
    }

    /**
     * Sets the value of the aiaucmIntegrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAIAUCMIntegrationId(String value) {
        this.aiaucmIntegrationId = value;
    }

    /**
     * Gets the value of the consumerLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerLink() {
        return consumerLink;
    }

    /**
     * Sets the value of the consumerLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerLink(String value) {
        this.consumerLink = value;
    }

    /**
     * Gets the value of the deceasedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeceasedDate() {
        return deceasedDate;
    }

    /**
     * Sets the value of the deceasedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeceasedDate(String value) {
        this.deceasedDate = value;
    }

    /**
     * Gets the value of the deathCertificateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeathCertificateNumber() {
        return deathCertificateNumber;
    }

    /**
     * Sets the value of the deathCertificateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeathCertificateNumber(String value) {
        this.deathCertificateNumber = value;
    }

    /**
     * Gets the value of the placeOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceOfDeath() {
        return placeOfDeath;
    }

    /**
     * Sets the value of the placeOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceOfDeath(String value) {
        this.placeOfDeath = value;
    }

    /**
     * Gets the value of the vaBenefit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVABenefit() {
        return vaBenefit;
    }

    /**
     * Sets the value of the vaBenefit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVABenefit(String value) {
        this.vaBenefit = value;
    }

    /**
     * Gets the value of the ethnicity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEthnicity() {
        return ethnicity;
    }

    /**
     * Sets the value of the ethnicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEthnicity(String value) {
        this.ethnicity = value;
    }

    /**
     * Gets the value of the classYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassYear() {
        return classYear;
    }

    /**
     * Sets the value of the classYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassYear(String value) {
        this.classYear = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegree(String value) {
        this.degree = value;
    }

    /**
     * Gets the value of the maritalStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaritalStatusDate() {
        return maritalStatusDate;
    }

    /**
     * Sets the value of the maritalStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaritalStatusDate(String value) {
        this.maritalStatusDate = value;
    }

    /**
     * Gets the value of the pendingReviewStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPendingReviewStatus() {
        return pendingReviewStatus;
    }

    /**
     * Sets the value of the pendingReviewStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPendingReviewStatus(String value) {
        this.pendingReviewStatus = value;
    }

    /**
     * Gets the value of the leadContactType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeadContactType() {
        return leadContactType;
    }

    /**
     * Sets the value of the leadContactType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeadContactType(String value) {
        this.leadContactType = value;
    }

    /**
     * Gets the value of the partyTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyTypeCode() {
        return partyTypeCode;
    }

    /**
     * Sets the value of the partyTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyTypeCode(String value) {
        this.partyTypeCode = value;
    }

    /**
     * Gets the value of the placeofBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceofBirth() {
        return placeofBirth;
    }

    /**
     * Sets the value of the placeofBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceofBirth(String value) {
        this.placeofBirth = value;
    }

    /**
     * Gets the value of the vaBenefits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVABenefits() {
        return vaBenefits;
    }

    /**
     * Sets the value of the vaBenefits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVABenefits(String value) {
        this.vaBenefits = value;
    }

    /**
     * Gets the value of the listOfContactCommunicationAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfContactCommunicationAddress }
     *     
     */
    public ListOfContactCommunicationAddress getListOfContactCommunicationAddress() {
        return listOfContactCommunicationAddress;
    }

    /**
     * Sets the value of the listOfContactCommunicationAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfContactCommunicationAddress }
     *     
     */
    public void setListOfContactCommunicationAddress(ListOfContactCommunicationAddress value) {
        this.listOfContactCommunicationAddress = value;
    }

    /**
     * Gets the value of the listOfContactAlternatePhone property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfContactAlternatePhone }
     *     
     */
    public ListOfContactAlternatePhone getListOfContactAlternatePhone() {
        return listOfContactAlternatePhone;
    }

    /**
     * Sets the value of the listOfContactAlternatePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfContactAlternatePhone }
     *     
     */
    public void setListOfContactAlternatePhone(ListOfContactAlternatePhone value) {
        this.listOfContactAlternatePhone = value;
    }

    /**
     * Gets the value of the listOfCuUcmHeConstituentName property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfCuUcmHeConstituentName }
     *     
     */
    public ListOfCuUcmHeConstituentName getListOfCuUcmHeConstituentName() {
        return listOfCuUcmHeConstituentName;
    }

    /**
     * Sets the value of the listOfCuUcmHeConstituentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfCuUcmHeConstituentName }
     *     
     */
    public void setListOfCuUcmHeConstituentName(ListOfCuUcmHeConstituentName value) {
        this.listOfCuUcmHeConstituentName = value;
    }

    /**
     * Gets the value of the listOfCIFContactReference property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfCIFContactReference }
     *     
     */
    public ListOfCIFContactReference getListOfCIFContactReference() {
        return listOfCIFContactReference;
    }

    /**
     * Sets the value of the listOfCIFContactReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfCIFContactReference }
     *     
     */
    public void setListOfCIFContactReference(ListOfCIFContactReference value) {
        this.listOfCIFContactReference = value;
    }

    /**
     * Gets the value of the listOfCuUcmHeConstituentIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfCuUcmHeConstituentIdentification }
     *     
     */
    public ListOfCuUcmHeConstituentIdentification getListOfCuUcmHeConstituentIdentification() {
        return listOfCuUcmHeConstituentIdentification;
    }

    /**
     * Sets the value of the listOfCuUcmHeConstituentIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfCuUcmHeConstituentIdentification }
     *     
     */
    public void setListOfCuUcmHeConstituentIdentification(ListOfCuUcmHeConstituentIdentification value) {
        this.listOfCuUcmHeConstituentIdentification = value;
    }

    /**
     * Gets the value of the listOfCuUcmHeConstituentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfCuUcmHeConstituentAddress }
     *     
     */
    public ListOfCuUcmHeConstituentAddress getListOfCuUcmHeConstituentAddress() {
        return listOfCuUcmHeConstituentAddress;
    }

    /**
     * Sets the value of the listOfCuUcmHeConstituentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfCuUcmHeConstituentAddress }
     *     
     */
    public void setListOfCuUcmHeConstituentAddress(ListOfCuUcmHeConstituentAddress value) {
        this.listOfCuUcmHeConstituentAddress = value;
    }

    /**
     * Gets the value of the listOfCuUcmHeConstituentAffiliation property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfCuUcmHeConstituentAffiliation }
     *     
     */
    public ListOfCuUcmHeConstituentAffiliation getListOfCuUcmHeConstituentAffiliation() {
        return listOfCuUcmHeConstituentAffiliation;
    }

    /**
     * Sets the value of the listOfCuUcmHeConstituentAffiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfCuUcmHeConstituentAffiliation }
     *     
     */
    public void setListOfCuUcmHeConstituentAffiliation(ListOfCuUcmHeConstituentAffiliation value) {
        this.listOfCuUcmHeConstituentAffiliation = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the searchspec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchspec() {
        return searchspec;
    }

    /**
     * Sets the value of the searchspec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchspec(String value) {
        this.searchspec = value;
    }

    /**
     * Gets the value of the contactStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactStatus() {
        return contactStatus;
    }

    /**
     * Sets the value of the contactStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactStatus(String value) {
        this.contactStatus = value;
    }

}
