//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 07:18:43 AM IST 
//


package com.lumendata.model.publish;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for Contact_AlternatePhone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Contact_AlternatePhone"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AlternatePhone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AlternatePhoneId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AlternatePhoneIntegrationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AlternatePhoneMediumType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AlternatePhoneName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AlternatePhoneUseType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Updated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EffectiveStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UpdatedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EffectiveEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LogicalDeleteFlg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AlternatePhoneEffectiveStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AlternatePhoneEffectiveEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ListOfCIFAlternatePhoneReference" type="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfCIFAlternatePhoneReference" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="IsPrimaryMVG" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Operation" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Searchspec" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Contact_AlternatePhone", propOrder = {
    "alternatePhone",
    "alternatePhoneId",
    "alternatePhoneIntegrationId",
    "alternatePhoneMediumType",
    "alternatePhoneName",
    "useType",
    "alternatePhoneUseType",
    "updated",
    "effectiveStartDate",
    "updatedBy",
    "effectiveEndDate",
    "logicalDeleteFlg",
    "alternatePhoneEffectiveStartDate",
    "alternatePhoneEffectiveEndDate",
    "listOfCIFAlternatePhoneReference"
})
public class ContactAlternatePhone {

    @XmlElement(name = "AlternatePhone", required = true)
    protected String alternatePhone;
    @XmlElement(name = "AlternatePhoneId")
    protected String alternatePhoneId;
    @XmlElement(name = "AlternatePhoneIntegrationId")
    protected String alternatePhoneIntegrationId;
    @XmlElement(name = "AlternatePhoneMediumType", required = true)
    protected String alternatePhoneMediumType;
    @XmlElement(name = "AlternatePhoneName")
    protected String alternatePhoneName;
    @XmlElement(name = "UseType")
    protected String useType;
    @XmlElement(name = "AlternatePhoneUseType")
    protected String alternatePhoneUseType;
    @XmlElement(name = "Updated")
    protected String updated;
    @XmlElement(name = "EffectiveStartDate")
    protected String effectiveStartDate;
    @XmlElement(name = "UpdatedBy")
    protected String updatedBy;
    @XmlElement(name = "EffectiveEndDate")
    protected String effectiveEndDate;
    @XmlElement(name = "LogicalDeleteFlg")
    protected String logicalDeleteFlg;
    @XmlElement(name = "AlternatePhoneEffectiveStartDate")
    protected String alternatePhoneEffectiveStartDate;
    @XmlElement(name = "AlternatePhoneEffectiveEndDate")
    protected String alternatePhoneEffectiveEndDate;
    @XmlElement(name = "ListOfCIFAlternatePhoneReference")
    protected ListOfCIFAlternatePhoneReference listOfCIFAlternatePhoneReference;
    @XmlAttribute(name = "IsPrimaryMVG")
    protected String isPrimaryMVG;
    @XmlAttribute(name = "Operation")
    protected String operation;
    @XmlAttribute(name = "Searchspec")
    protected String searchspec;

    /**
     * Gets the value of the alternatePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePhone() {
        return alternatePhone;
    }

    /**
     * Sets the value of the alternatePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePhone(String value) {
        this.alternatePhone = value;
    }

    /**
     * Gets the value of the alternatePhoneId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePhoneId() {
        return alternatePhoneId;
    }

    /**
     * Sets the value of the alternatePhoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePhoneId(String value) {
        this.alternatePhoneId = value;
    }

    /**
     * Gets the value of the alternatePhoneIntegrationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePhoneIntegrationId() {
        return alternatePhoneIntegrationId;
    }

    /**
     * Sets the value of the alternatePhoneIntegrationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePhoneIntegrationId(String value) {
        this.alternatePhoneIntegrationId = value;
    }

    /**
     * Gets the value of the alternatePhoneMediumType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePhoneMediumType() {
        return alternatePhoneMediumType;
    }

    /**
     * Sets the value of the alternatePhoneMediumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePhoneMediumType(String value) {
        this.alternatePhoneMediumType = value;
    }

    /**
     * Gets the value of the alternatePhoneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePhoneName() {
        return alternatePhoneName;
    }

    /**
     * Sets the value of the alternatePhoneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePhoneName(String value) {
        this.alternatePhoneName = value;
    }

    /**
     * Gets the value of the useType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseType() {
        return useType;
    }

    /**
     * Sets the value of the useType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseType(String value) {
        this.useType = value;
    }

    /**
     * Gets the value of the alternatePhoneUseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePhoneUseType() {
        return alternatePhoneUseType;
    }

    /**
     * Sets the value of the alternatePhoneUseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePhoneUseType(String value) {
        this.alternatePhoneUseType = value;
    }

    /**
     * Gets the value of the updated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdated() {
        return updated;
    }

    /**
     * Sets the value of the updated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdated(String value) {
        this.updated = value;
    }

    /**
     * Gets the value of the effectiveStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveStartDate() {
        return effectiveStartDate;
    }

    /**
     * Sets the value of the effectiveStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveStartDate(String value) {
        this.effectiveStartDate = value;
    }

    /**
     * Gets the value of the updatedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * Sets the value of the updatedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdatedBy(String value) {
        this.updatedBy = value;
    }

    /**
     * Gets the value of the effectiveEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveEndDate() {
        return effectiveEndDate;
    }

    /**
     * Sets the value of the effectiveEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveEndDate(String value) {
        this.effectiveEndDate = value;
    }

    /**
     * Gets the value of the logicalDeleteFlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalDeleteFlg() {
        return logicalDeleteFlg;
    }

    /**
     * Sets the value of the logicalDeleteFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalDeleteFlg(String value) {
        this.logicalDeleteFlg = value;
    }

    /**
     * Gets the value of the alternatePhoneEffectiveStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePhoneEffectiveStartDate() {
        return alternatePhoneEffectiveStartDate;
    }

    /**
     * Sets the value of the alternatePhoneEffectiveStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePhoneEffectiveStartDate(String value) {
        this.alternatePhoneEffectiveStartDate = value;
    }

    /**
     * Gets the value of the alternatePhoneEffectiveEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePhoneEffectiveEndDate() {
        return alternatePhoneEffectiveEndDate;
    }

    /**
     * Sets the value of the alternatePhoneEffectiveEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePhoneEffectiveEndDate(String value) {
        this.alternatePhoneEffectiveEndDate = value;
    }

    /**
     * Gets the value of the listOfCIFAlternatePhoneReference property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfCIFAlternatePhoneReference }
     *     
     */
    public ListOfCIFAlternatePhoneReference getListOfCIFAlternatePhoneReference() {
        return listOfCIFAlternatePhoneReference;
    }

    /**
     * Sets the value of the listOfCIFAlternatePhoneReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfCIFAlternatePhoneReference }
     *     
     */
    public void setListOfCIFAlternatePhoneReference(ListOfCIFAlternatePhoneReference value) {
        this.listOfCIFAlternatePhoneReference = value;
    }

    /**
     * Gets the value of the isPrimaryMVG property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPrimaryMVG() {
        return isPrimaryMVG;
    }

    /**
     * Sets the value of the isPrimaryMVG property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPrimaryMVG(String value) {
        this.isPrimaryMVG = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the searchspec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchspec() {
        return searchspec;
    }

    /**
     * Sets the value of the searchspec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchspec(String value) {
        this.searchspec = value;
    }

}
