//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 07:18:43 AM IST 
//


package com.lumendata.model.publish;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ListOfContact_CommunicationAddress complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListOfContact_CommunicationAddress"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Contact_CommunicationAddress" type="{http://www.siebel.com/xml/SwiPersonPublishIO}Contact_CommunicationAddress" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListOfContact_CommunicationAddress", propOrder = {
    "contactCommunicationAddress"
})
public class ListOfContactCommunicationAddress {

    @XmlElement(name = "Contact_CommunicationAddress")
    protected List<ContactCommunicationAddress> contactCommunicationAddress;

    /**
     * Gets the value of the contactCommunicationAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactCommunicationAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactCommunicationAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactCommunicationAddress }
     * 
     * 
     */
    public List<ContactCommunicationAddress> getContactCommunicationAddress() {
        if (contactCommunicationAddress == null) {
            contactCommunicationAddress = new ArrayList<ContactCommunicationAddress>();
        }
        return this.contactCommunicationAddress;
    }

}
