//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 07:18:43 AM IST 
//


package com.lumendata.model.publish;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lumendata.model.publish package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListOfSwiPersonPublishIO_QNAME = new QName("http://www.siebel.com/xml/SwiPersonPublishIO", "ListOfSwiPersonPublishIO");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lumendata.model.publish
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Security }
     * 
     */
    public Security createSecurity() {
        return new Security();
    }

    /**
     * Create an instance of {@link ListOfSwiPersonPublishIO }
     * 
     */
    public ListOfSwiPersonPublishIO createListOfSwiPersonPublishIO() {
        return new ListOfSwiPersonPublishIO();
    }

    /**
     * Create an instance of {@link ListOfSwiPersonPublishIOTopElmt }
     * 
     */
    public ListOfSwiPersonPublishIOTopElmt createListOfSwiPersonPublishIOTopElmt() {
        return new ListOfSwiPersonPublishIOTopElmt();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link ListOfContactCommunicationAddress }
     * 
     */
    public ListOfContactCommunicationAddress createListOfContactCommunicationAddress() {
        return new ListOfContactCommunicationAddress();
    }

    /**
     * Create an instance of {@link ContactCommunicationAddress }
     * 
     */
    public ContactCommunicationAddress createContactCommunicationAddress() {
        return new ContactCommunicationAddress();
    }

    /**
     * Create an instance of {@link ListOfContactAlternatePhone }
     * 
     */
    public ListOfContactAlternatePhone createListOfContactAlternatePhone() {
        return new ListOfContactAlternatePhone();
    }

    /**
     * Create an instance of {@link ContactAlternatePhone }
     * 
     */
    public ContactAlternatePhone createContactAlternatePhone() {
        return new ContactAlternatePhone();
    }

    /**
     * Create an instance of {@link ListOfCuUcmHeConstituentName }
     * 
     */
    public ListOfCuUcmHeConstituentName createListOfCuUcmHeConstituentName() {
        return new ListOfCuUcmHeConstituentName();
    }

    /**
     * Create an instance of {@link CuUcmHeConstituentName }
     * 
     */
    public CuUcmHeConstituentName createCuUcmHeConstituentName() {
        return new CuUcmHeConstituentName();
    }

    /**
     * Create an instance of {@link ListOfCIFContactReference }
     * 
     */
    public ListOfCIFContactReference createListOfCIFContactReference() {
        return new ListOfCIFContactReference();
    }

    /**
     * Create an instance of {@link CIFContactReference }
     * 
     */
    public CIFContactReference createCIFContactReference() {
        return new CIFContactReference();
    }

    /**
     * Create an instance of {@link ListOfCuUcmHeConstituentIdentification }
     * 
     */
    public ListOfCuUcmHeConstituentIdentification createListOfCuUcmHeConstituentIdentification() {
        return new ListOfCuUcmHeConstituentIdentification();
    }

    /**
     * Create an instance of {@link CuUcmHeConstituentIdentification }
     * 
     */
    public CuUcmHeConstituentIdentification createCuUcmHeConstituentIdentification() {
        return new CuUcmHeConstituentIdentification();
    }

    /**
     * Create an instance of {@link ListOfCuUcmHeConstituentAddress }
     * 
     */
    public ListOfCuUcmHeConstituentAddress createListOfCuUcmHeConstituentAddress() {
        return new ListOfCuUcmHeConstituentAddress();
    }

    /**
     * Create an instance of {@link CuUcmHeConstituentAddress }
     * 
     */
    public CuUcmHeConstituentAddress createCuUcmHeConstituentAddress() {
        return new CuUcmHeConstituentAddress();
    }

    /**
     * Create an instance of {@link ListOfCuUcmHeConstituentAffiliation }
     * 
     */
    public ListOfCuUcmHeConstituentAffiliation createListOfCuUcmHeConstituentAffiliation() {
        return new ListOfCuUcmHeConstituentAffiliation();
    }

    /**
     * Create an instance of {@link CuUcmHeConstituentAffiliation }
     * 
     */
    public CuUcmHeConstituentAffiliation createCuUcmHeConstituentAffiliation() {
        return new CuUcmHeConstituentAffiliation();
    }

    /**
     * Create an instance of {@link ListOfCIFCommunicationAddressReference }
     * 
     */
    public ListOfCIFCommunicationAddressReference createListOfCIFCommunicationAddressReference() {
        return new ListOfCIFCommunicationAddressReference();
    }

    /**
     * Create an instance of {@link CIFCommunicationAddressReference }
     * 
     */
    public CIFCommunicationAddressReference createCIFCommunicationAddressReference() {
        return new CIFCommunicationAddressReference();
    }

    /**
     * Create an instance of {@link ListOfCIFAlternatePhoneReference }
     * 
     */
    public ListOfCIFAlternatePhoneReference createListOfCIFAlternatePhoneReference() {
        return new ListOfCIFAlternatePhoneReference();
    }

    /**
     * Create an instance of {@link CIFAlternatePhoneReference }
     * 
     */
    public CIFAlternatePhoneReference createCIFAlternatePhoneReference() {
        return new CIFAlternatePhoneReference();
    }

    /**
     * Create an instance of {@link ListOfCIFContactNameReference }
     * 
     */
    public ListOfCIFContactNameReference createListOfCIFContactNameReference() {
        return new ListOfCIFContactNameReference();
    }

    /**
     * Create an instance of {@link CIFContactNameReference }
     * 
     */
    public CIFContactNameReference createCIFContactNameReference() {
        return new CIFContactNameReference();
    }

    /**
     * Create an instance of {@link CustomHeaderContext }
     * 
     */
    public CustomHeaderContext createCustomHeaderContext() {
        return new CustomHeaderContext();
    }

    /**
     * Create an instance of {@link PersonPublishOperationInput }
     * 
     */
    public PersonPublishOperationInput createPersonPublishOperationInput() {
        return new PersonPublishOperationInput();
    }

    /**
     * Create an instance of {@link XMLHierarchyOutput }
     * 
     */
    public XMLHierarchyOutput createXMLHierarchyOutput() {
        return new XMLHierarchyOutput();
    }

    /**
     * Create an instance of {@link PersonPublishOperationOutput }
     * 
     */
    public PersonPublishOperationOutput createPersonPublishOperationOutput() {
        return new PersonPublishOperationOutput();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListOfSwiPersonPublishIO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ListOfSwiPersonPublishIO }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.siebel.com/xml/SwiPersonPublishIO", name = "ListOfSwiPersonPublishIO")
    public JAXBElement<ListOfSwiPersonPublishIO> createListOfSwiPersonPublishIO(ListOfSwiPersonPublishIO value) {
        return new JAXBElement<ListOfSwiPersonPublishIO>(_ListOfSwiPersonPublishIO_QNAME, ListOfSwiPersonPublishIO.class, null, value);
    }

}
