//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.18 at 07:18:43 AM IST 
//


package com.lumendata.model.publish;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{Sys_Mdm_All_PersonPublish}CustomHeaderContext" minOccurs="0"/&gt;
 *         &lt;element ref="{http://schemas.xmlsoap.org/ws/2002/07/secext}Security" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.siebel.com/xml/SwiPersonPublishIO}ListOfSwiPersonPublishIO" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customHeaderContext",
    "security",
    "listOfSwiPersonPublishIO"
})
@XmlRootElement(name = "PersonPublishOperation_Input", namespace = "Sys_Mdm_All_PersonPublish")
public class PersonPublishOperationInput {

    @XmlElement(name = "CustomHeaderContext", namespace = "Sys_Mdm_All_PersonPublish")
    protected CustomHeaderContext customHeaderContext;
    @XmlElement(name = "Security", namespace = "http://schemas.xmlsoap.org/ws/2002/07/secext")
    protected Security security;
    @XmlElement(name = "ListOfSwiPersonPublishIO")
    protected ListOfSwiPersonPublishIO listOfSwiPersonPublishIO;

    /**
     * Gets the value of the customHeaderContext property.
     * 
     * @return
     *     possible object is
     *     {@link CustomHeaderContext }
     *     
     */
    public CustomHeaderContext getCustomHeaderContext() {
        return customHeaderContext;
    }

    /**
     * Sets the value of the customHeaderContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomHeaderContext }
     *     
     */
    public void setCustomHeaderContext(CustomHeaderContext value) {
        this.customHeaderContext = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Security }
     *     
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setSecurity(Security value) {
        this.security = value;
    }

    /**
     * Gets the value of the listOfSwiPersonPublishIO property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfSwiPersonPublishIO }
     *     
     */
    public ListOfSwiPersonPublishIO getListOfSwiPersonPublishIO() {
        return listOfSwiPersonPublishIO;
    }

    /**
     * Sets the value of the listOfSwiPersonPublishIO property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfSwiPersonPublishIO }
     *     
     */
    public void setListOfSwiPersonPublishIO(ListOfSwiPersonPublishIO value) {
        this.listOfSwiPersonPublishIO = value;
    }

}
