spring:
  application:
    name: general-publish
  data:
    neo4j:
      password: neo4j
      uri: bolt+routing://127.0.0.1:7687
      username: neo4j
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
      group-id: general-publish-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

regular:
  publish:
    topic: regular-publish-topic
general:
  mv:
    topic: general-mv-topic
server:
  port: 8099
